"""Starting automation state for a tenant that has not configured anything yet.

Same convention as finops/seed.py and drift/seed.py: representative content so the screen
has something to act on, owned by the tenant the moment they edit it. These rules and
models describe what the platform ships with; the numbers on them are starting points, not
measurements, and every one is replaced by real counters as soon as a rule executes.
"""

from __future__ import annotations

from typing import Any


def seed_state() -> dict[str, Any]:
    return {
        "settings": {
            "enabled": True,
            # Below this confidence a rule proposes rather than acts.
            "auto_approve_confidence": 90,
            "require_approval_for_critical": True,
            "updated_at": None,
        },
        "rules": [
            {
                "id": "rule-memory-restart",
                "name": "Memory Threshold Auto-Restart",
                "description": "Automatically restart services when memory usage exceeds 90% for 5 minutes",
                "category": "Infrastructure",
                "trigger": "Memory > 90% for 5min",
                "action": "Restart service + Clear cache",
                "status": "active",
                "enabled": True,
                "ai_driven": True,
                "confidence": 95,
                "execution_count": 0,
                "success_count": 0,
                "success_rate": 0.0,
                "avg_resolution_seconds": None,
                "last_triggered": None,
                "created_at": None,
            },
            {
                "id": "rule-db-pool",
                "name": "Database Connection Pool Recovery",
                "description": "Reset connection pools when the timeout rate exceeds threshold, restarting the database only if it stays critical",
                "category": "Database",
                "trigger": "Connection timeout > 10% for 3min",
                "action": "Reset pool + Scale connections",
                "status": "active",
                "enabled": True,
                "ai_driven": True,
                "confidence": 92,
                "execution_count": 0,
                "success_count": 0,
                "success_rate": 0.0,
                "avg_resolution_seconds": None,
                "last_triggered": None,
                "created_at": None,
            },
            {
                "id": "rule-cpu-lb",
                "name": "CPU Spike Load Balancer Adjustment",
                "description": "Redistribute traffic when CPU spikes are detected on a single node",
                "category": "Performance",
                "trigger": "CPU > 85% on single node",
                "action": "Adjust load balancer weights",
                "status": "learning",
                "enabled": True,
                "ai_driven": True,
                "confidence": 78,
                "execution_count": 0,
                "success_count": 0,
                "success_rate": 0.0,
                "avg_resolution_seconds": None,
                "last_triggered": None,
                "created_at": None,
            },
            {
                "id": "rule-disk-cleanup",
                "name": "Disk Space Cleanup Automation",
                "description": "Clean temporary files and rotate logs when disk usage exceeds 85%",
                "category": "Infrastructure",
                "trigger": "Disk usage > 85%",
                "action": "Clean temp files + Rotate logs",
                "status": "active",
                "enabled": True,
                "ai_driven": False,
                "confidence": 98,
                "execution_count": 0,
                "success_count": 0,
                "success_rate": 0.0,
                "avg_resolution_seconds": None,
                "last_triggered": None,
                "created_at": None,
            },
        ],
        "executions": [],
        "models": [
            {
                "id": "model-memory-leak",
                "name": "Memory Leak Prediction",
                "description": "LSTM network over memory-usage windows, flagging gradual leak patterns before they page anyone",
                "type": "Time Series Analysis",
                "algorithm": "LSTM + Gradient Boosting",
                "accuracy": 94.2,
                "predictions": 0,
                "status": "active",
                "enabled": True,
                "features": ["Memory usage patterns", "GC frequency", "Heap size trends", "Application load"],
                "implementation": "Agents report memory metrics every 30s. The model scores sliding one-hour windows and raises a predictive alert above 85% confidence.",
                "training_data": "Six months of production memory metrics",
                "retraining": "Weekly",
                "last_trained": None,
            },
            {
                "id": "model-anomaly",
                "name": "Performance Anomaly Detection",
                "description": "Isolation Forest with statistical process control over per-service baselines",
                "type": "Anomaly Detection",
                "algorithm": "Isolation Forest + SPC",
                "accuracy": 91.8,
                "predictions": 0,
                "status": "active",
                "enabled": True,
                "features": ["Response times", "Throughput", "Error rates", "Resource utilization"],
                "implementation": "Learns a baseline per service and scores deviations continuously, with concept-drift detection on the baseline itself.",
                "training_data": "Streaming APM data",
                "retraining": "Continuous online learning",
                "last_trained": None,
            },
            {
                "id": "model-capacity",
                "name": "Capacity Planning",
                "description": "Prophet forecast of resource need from historical trend and seasonality",
                "type": "Forecasting",
                "algorithm": "Prophet + Linear Regression",
                "accuracy": 87.3,
                "predictions": 0,
                "status": "active",
                "enabled": True,
                "features": ["Historical resource usage", "Business metrics", "Seasonal patterns", "Growth trends"],
                "implementation": "Combines time-series forecasting with business context, accounting for seasonality and known events.",
                "training_data": "Two years of infrastructure metrics against business KPIs",
                "retraining": "Monthly",
                "last_trained": None,
            },
            {
                "id": "model-rca",
                "name": "Root Cause Analysis Engine",
                "description": "Graph neural network over the service dependency graph, correlating incidents to a likely cause",
                "type": "Graph Analysis",
                "algorithm": "Graph Neural Network + Causal Inference",
                "accuracy": 89.5,
                "predictions": 0,
                "status": "active",
                "enabled": True,
                "features": ["Service topology", "Error correlations", "Timing patterns", "Dependency chains"],
                "implementation": "Propagates incident signal across the live dependency graph and ranks root-cause hypotheses by causal score.",
                "training_data": "Historical incidents with verified root causes",
                "retraining": "Bi-weekly",
                "last_trained": None,
            },
            {
                "id": "model-security",
                "name": "Security Threat Prediction",
                "description": "Ensemble of behavioural analysis and threat intelligence",
                "type": "Security Analytics",
                "algorithm": "Random Forest + Deep Learning + Rules",
                "accuracy": 96.1,
                "predictions": 0,
                "status": "active",
                "enabled": True,
                "features": ["User behaviour", "Network traffic", "Access logs", "Threat intelligence"],
                "implementation": "Supervised detection for known threats alongside unsupervised scoring for novel ones.",
                "training_data": "Enterprise security logs plus external threat feeds",
                "retraining": "Daily",
                "last_trained": None,
            },
        ],
        "training_runs": [],
        "insights": [
            {
                "id": "insight-memory-leak",
                "title": "Memory Leak Pattern Detected",
                "description": "user-service shows a gradual memory increase pattern. Predicted failure in about four hours.",
                "severity": "warning",
                "confidence": 87,
                "time_to_impact": "4 hours",
                "recommended_action": "Schedule a proactive restart during the low-traffic window",
                "category": "Predictive",
                "source_model": "model-memory-leak",
                "status": "pending",
                "decided_by": None,
                "decided_at": None,
            },
            {
                "id": "insight-db-degradation",
                "title": "Database Performance Degradation",
                "description": "Query response times are trending upward; user-visible impact expected within two hours.",
                "severity": "critical",
                "confidence": 92,
                "time_to_impact": "2 hours",
                "recommended_action": "Optimise the slow queries and scale the connection pool",
                "category": "Performance",
                "source_model": "model-anomaly",
                "status": "pending",
                "decided_by": None,
                "decided_at": None,
            },
            {
                "id": "insight-traffic-surge",
                "title": "Traffic Surge Predicted",
                "description": "Historical patterns suggest a 40% traffic increase within the hour.",
                "severity": "info",
                "confidence": 78,
                "time_to_impact": "1 hour",
                "recommended_action": "Pre-scale the fleet and warm the caches",
                "category": "Capacity",
                "source_model": "model-capacity",
                "status": "pending",
                "decided_by": None,
                "decided_at": None,
            },
        ],
        "agents": [],
    }
